name: Atlas Workflow

on:
  push:
    branches:
      - main

jobs:
  atlas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Python Version
        run: python --version

      - name: Hello Atlas
        run: echo "Hello Atlas!"